In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[2.0362e-19, 4.9569e+33, 2.0193e-19],
        [4.2951e+24, 1.7866e+25, 6.6635e-33],
        [4.3612e+27, 8.7518e-04, 1.1692e-19],
        [1.5637e-01, 1.3000e+34, 5.0782e+31],
        [4.2964e+24, 2.7944e+20, 1.2734e-14]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.4291, 0.5841, 0.8863],
        [0.5343, 0.4461, 0.3762],
        [0.7296, 0.1708, 0.3496],
        [0.9728, 0.9730, 0.9080],
        [0.9256, 0.7843, 0.2624]])


In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0454,  0.2893, -1.6613],
        [ 0.3727, -0.5649, -0.2208],
        [ 0.2568,  1.1826,  0.9300],
        [-1.5254, -1.0812, -1.0497],
        [-0.2969,  1.1319,  0.7508]])


In [10]:
print(x.size())

print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


算术操作

In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.8791,  0.6874, -1.0183],
        [ 0.9188, -0.4296,  0.7785],
        [ 1.0185,  1.9895,  1.6307],
        [-1.4160, -0.6949, -0.3417],
        [ 0.1788,  1.2611,  1.4612]])


In [12]:
print(torch.add(x,y))

tensor([[-0.8791,  0.6874, -1.0183],
        [ 0.9188, -0.4296,  0.7785],
        [ 1.0185,  1.9895,  1.6307],
        [-1.4160, -0.6949, -0.3417],
        [ 0.1788,  1.2611,  1.4612]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.8791,  0.6874, -1.0183],
        [ 0.9188, -0.4296,  0.7785],
        [ 1.0185,  1.9895,  1.6307],
        [-1.4160, -0.6949, -0.3417],
        [ 0.1788,  1.2611,  1.4612]])


In [14]:
print(y)
y.add_(x)   #adds x to y
print(y)

tensor([[0.1663, 0.3981, 0.6430],
        [0.5461, 0.1353, 0.9993],
        [0.7616, 0.8069, 0.7007],
        [0.1094, 0.3863, 0.7080],
        [0.4757, 0.1292, 0.7104]])
tensor([[-0.8791,  0.6874, -1.0183],
        [ 0.9188, -0.4296,  0.7785],
        [ 1.0185,  1.9895,  1.6307],
        [-1.4160, -0.6949, -0.3417],
        [ 0.1788,  1.2611,  1.4612]])


索引

In [15]:
print('y',y)
print('x',x)
y = x[0,:] #浅拷贝
y += 1
print(y)
print(x[0,:])

y tensor([[-0.8791,  0.6874, -1.0183],
        [ 0.9188, -0.4296,  0.7785],
        [ 1.0185,  1.9895,  1.6307],
        [-1.4160, -0.6949, -0.3417],
        [ 0.1788,  1.2611,  1.4612]])
x tensor([[-1.0454,  0.2893, -1.6613],
        [ 0.3727, -0.5649, -0.2208],
        [ 0.2568,  1.1826,  0.9300],
        [-1.5254, -1.0812, -1.0497],
        [-0.2969,  1.1319,  0.7508]])
tensor([-0.0454,  1.2893, -0.6613])
tensor([-0.0454,  1.2893, -0.6613])


改变形状

In [16]:
print(y)
print(x)
y = x.view(15)
z = x.view(-1,5) #-1表示推理维度
print(x.size(),y.size(),z.size())

tensor([-0.0454,  1.2893, -0.6613])
tensor([[-0.0454,  1.2893, -0.6613],
        [ 0.3727, -0.5649, -0.2208],
        [ 0.2568,  1.1826,  0.9300],
        [-1.5254, -1.0812, -1.0497],
        [-0.2969,  1.1319,  0.7508]])
torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [17]:
x += 1
print(x)
print(y) 

tensor([[ 0.9546,  2.2893,  0.3387],
        [ 1.3727,  0.4351,  0.7792],
        [ 1.2568,  2.1826,  1.9300],
        [-0.5254, -0.0812, -0.0497],
        [ 0.7031,  2.1319,  1.7508]])
tensor([ 0.9546,  2.2893,  0.3387,  1.3727,  0.4351,  0.7792,  1.2568,  2.1826,
         1.9300, -0.5254, -0.0812, -0.0497,  0.7031,  2.1319,  1.7508])


In [18]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[-0.0454,  1.2893, -0.6613],
        [ 0.3727, -0.5649, -0.2208],
        [ 0.2568,  1.1826,  0.9300],
        [-1.5254, -1.0812, -1.0497],
        [-0.2969,  1.1319,  0.7508]])
tensor([ 0.9546,  2.2893,  0.3387,  1.3727,  0.4351,  0.7792,  1.2568,  2.1826,
         1.9300, -0.5254, -0.0812, -0.0497,  0.7031,  2.1319,  1.7508])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0412])
-1.0411995649337769


线性代数

广播机制

In [20]:
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


运算的内存开销

In [21]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)  
y = y + x    #有了新的内存
print(id(y) == id_before) #False

False


In [22]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)

y[:] = y + x  #替换原内存的内容

print(id(y) == id_before)

True


In [24]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)

torch.add(x,y,out=y) #替换原内存的内容

print(id(y) == id_before)

True


### Tensor 和 NumPy 互相转换

Tensor转NumPy

In [28]:
a = torch.ones(5)
print(a)
b = a.numpy()  #共享地址
print(b)

a += 1
print(a,b)

b += 1
print(a,b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


Numpy数组转Tensor

In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

a += 1
print(a,b)
b += 1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [30]:
c = torch.tensor(a)
a += 1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


Tensor on GPU

In [31]:
if torch.cuda.is_available():
    device = torch.device("cuda")   #GPU
    y = torch.ones_like(x,device=device)  #在device上创建一个y
    x = x.to(device)                      #等价于.to("cuda")
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))       #to()还可以同时更改数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


### 自动求梯度

概念

Tensor

In [32]:
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [33]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [34]:
print(x.is_leaf,y.is_leaf)

True False


In [35]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [36]:
a = torch.randn(2,2)
a = ((a * 3)/(a -1))
print(a.requires_grad)
a.requires_grad_(True)  # .requires_grad 为一个标志位，一个数值
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


梯度

In [37]:
out.backward()

In [38]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [61]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([2.])
tensor([1.])


In [62]:
x = torch.tensor([1,2.0,3.0,4.0],requires_grad = True)
y = 2 * x
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [68]:
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
print(v.size(),z.size())
#z.grad.data.zero_()
#z.backward(v)  #只能进行一次求导，重复求导会出错
print(x.grad)

torch.Size([2, 2]) torch.Size([2, 2])
None


In [66]:
x = torch.tensor(1.0,requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [58]:
y3.backward()
print(x.grad)

tensor(2.)


In [59]:
x = torch.ones(1,requires_grad=True)

print(x.data)
print(x.data.requires_grad)

y = 2 * x
x.data *= 100

y.backward()

print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
