In [1]:
import torch

### 数据操作

#### 入门

In [3]:
x = torch.arange(12) #创建行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape #输出x的形状

torch.Size([12])

In [8]:
x.size()  #行向量的shape和size一样

torch.Size([12])

In [9]:
x.numel() #返回数组中元素的个数

12

In [10]:
X = x.reshape(3,4) #改变形状，但是元素值一样
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
x.reshape(-1,4),x.reshape(3,-1),x.reshape(3,4)  #-1表示通过计算获得行数或者列数

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [12]:
torch.zeros((2,3,4)) #全0矩阵，矩阵维度用元组传入

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3,4) #均值为0,标准差为1的正太分布随机

tensor([[ 0.6644, -0.6229, -0.9831,  2.5946],
        [ 0.5375, -0.4918, -0.9243,  1.5989],
        [ 1.2607, -0.8528,  0.0666, -0.0624]])

In [16]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])  
#通过列表创建tensor

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
[[2,1,4,3],[1,2,3,4],[4,3,2,1]]

[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]

#### 运算符

In [21]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y,x - y,x * y, x / y, x ** y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [22]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [23]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

In [24]:
torch.cat((X,Y),dim=0) #扩展行

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [25]:
torch.cat((X,Y),dim=1) #扩展列

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [26]:
X == Y #按元素判断

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()  #所有元素求和

tensor(66.)

#### 广播机制

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状。
2. 对生成的数组执行按元素操作

In [28]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
a + b #广播机制

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [30]:
a = torch.ones(3,1,2)
b = torch.ones(2,1)
#广播时，从尾部遍历维度，1对应2,2对应1,3对应不存在
(a+b).size()

torch.Size([3, 2, 2])

#### 索引和切片

In [31]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
X[-1] #最后一个元素


tensor([ 8.,  9., 10., 11.])

In [34]:
X[1:3] #第二个元素和第三个元素

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X[1,2] = 9 #写入操作
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

#### 节省内存

In [37]:
before = id(Y)
Y = X + Y
id(Y) == before

False

In [38]:
Z = torch.zeros_like(Y) #安装Y的形状创建全0矩阵
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 139770550679088
id(Z): 139770550679088


In [39]:
before = id(X)
X += Y
id(X) == before


True

In [40]:
before = id(X)
X = X + Y  #注意和前一个操作对比，此操作会使用新内存，钱一个不会
id(X) == before

False

#### 转换为其他Python对象

In [41]:
A = X.numpy()  #tensor转为numpy
B = torch.tensor(A) #numpy转为tensor
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 数据预处理

介绍pandas预处理原始数据，并且转为tensor

#### 读取数据集

In [44]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')

with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n') #每行表示一个样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [45]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


#### 处理缺失值

In [49]:
from unicodedata import numeric


inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]  #前两列为输入，最后一列为u输出
inputs = inputs.fillna(inputs.mean())  #填充NaN，使用均值
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/tmp/ipykernel_11262/1328826892.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())  #填充NaN，使用均值


In [50]:
inputs = pd.get_dummies(inputs,dummy_na=True) #是利用pandas实现one hot encode的方式
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


#### 转换为张量格式

In [51]:
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [53]:
inputs.values,outputs.values

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]]),
 array([127500, 106000, 178100, 140000]))