In [2]:
a = 1
b = 1
c = a + 0
id(a) == id(b) 

True

In [3]:
import torch

In [8]:
a = torch.Tensor([[1,2,3],[4,5,6]])
torch.split(a,[3],1)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),)

In [14]:
torch.where(a>1,torch.full_like(a,10),a)

tensor([[ 1., 10., 10.],
        [10., 10., 10.]])

In [11]:
torch.full_like(a,2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [15]:
a = torch.Tensor([[1,2,3],[4,5,6]])

In [17]:
a.clamp(2,5)

tensor([[2., 2., 3.],
        [4., 5., 5.]])

In [18]:
a = torch.arange(1,4)

In [19]:
a

tensor([1, 2, 3])

In [20]:
a.unsqueeze(0)

tensor([[1, 2, 3]])

In [21]:
a.unsqueeze(0).shape

torch.Size([1, 3])

In [22]:
a.unsqueeze(0).squeeze(0).shape

torch.Size([3])

In [24]:
a = torch.randn(3,3)
a

tensor([[ 0.7994,  0.3998,  0.4171],
        [-0.6773,  0.0624,  0.1177],
        [ 0.5121, -0.3942, -0.0576]])

In [25]:
a.sort(1,True)

torch.return_types.sort(
values=tensor([[ 0.7994,  0.4171,  0.3998],
        [ 0.1177,  0.0624, -0.6773],
        [ 0.5121, -0.0576, -0.3942]]),
indices=tensor([[0, 2, 1],
        [2, 1, 0],
        [0, 2, 1]]))

In [27]:
a.sort(0,False)

torch.return_types.sort(
values=tensor([[-0.6773, -0.3942, -0.0576],
        [ 0.5121,  0.0624,  0.1177],
        [ 0.7994,  0.3998,  0.4171]]),
indices=tensor([[1, 2, 2],
        [2, 1, 1],
        [0, 0, 0]]))

In [1]:
from torch import nn

In [5]:
conv = nn.Conv2d(in_channels = 1,out_channels=1,kernel_size=3,stride=1,padding=1,dilation=1,bias=True)

In [6]:
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [7]:
conv.weight.shape

torch.Size([1, 1, 3, 3])