In [2]:
a = 1
b = 1
c = a + 0
id(a) == id(b) 

True

In [3]:
import torch

In [8]:
a = torch.Tensor([[1,2,3],[4,5,6]])
torch.split(a,[3],1)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),)

In [14]:
torch.where(a>1,torch.full_like(a,10),a)

tensor([[ 1., 10., 10.],
        [10., 10., 10.]])

In [11]:
torch.full_like(a,2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [15]:
a = torch.Tensor([[1,2,3],[4,5,6]])

In [17]:
a.clamp(2,5)

tensor([[2., 2., 3.],
        [4., 5., 5.]])