In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[2.3607e-09, 1.3532e+22, 1.3085e-11],
        [1.0625e+21, 3.3527e-09, 1.0990e-05],
        [1.6986e+22, 2.6965e+23, 2.6312e+20],
        [2.4286e-18, 1.8788e+31, 7.9303e+34],
        [6.1949e-04, 4.6304e+27, 7.2707e+31]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.6304, 0.9485, 0.9881],
        [0.5544, 0.9468, 0.9321],
        [0.3469, 0.7024, 0.6843],
        [0.7306, 0.5367, 0.5335],
        [0.3148, 0.2122, 0.2487]])


In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8062, -0.2020,  1.3435],
        [ 0.3545, -0.3792, -0.0135],
        [ 0.1558, -0.2548,  0.9685],
        [-0.4567,  0.1660,  0.5115],
        [-0.7268,  0.4110, -0.3440]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 1.6648,  0.2099,  2.0755],
        [ 0.6719, -0.0472,  0.6412],
        [ 1.0586,  0.3329,  1.3632],
        [-0.0416,  0.3354,  0.9345],
        [-0.5169,  1.2571, -0.3132]])


In [12]:
print(torch.add(x,y))

tensor([[ 1.6648,  0.2099,  2.0755],
        [ 0.6719, -0.0472,  0.6412],
        [ 1.0586,  0.3329,  1.3632],
        [-0.0416,  0.3354,  0.9345],
        [-0.5169,  1.2571, -0.3132]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.6648,  0.2099,  2.0755],
        [ 0.6719, -0.0472,  0.6412],
        [ 1.0586,  0.3329,  1.3632],
        [-0.0416,  0.3354,  0.9345],
        [-0.5169,  1.2571, -0.3132]])


In [14]:
y.add_(x)
print(x)
print(y)

tensor([[ 0.8062, -0.2020,  1.3435],
        [ 0.3545, -0.3792, -0.0135],
        [ 0.1558, -0.2548,  0.9685],
        [-0.4567,  0.1660,  0.5115],
        [-0.7268,  0.4110, -0.3440]])
tensor([[ 1.6648,  0.2099,  2.0755],
        [ 0.6719, -0.0472,  0.6412],
        [ 1.0586,  0.3329,  1.3632],
        [-0.0416,  0.3354,  0.9345],
        [-0.5169,  1.2571, -0.3132]])


In [15]:
print(x[:,1])

tensor([-0.2020, -0.3792, -0.2548,  0.1660,  0.4110])


In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1786])
-0.17856639623641968


In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))

tensor([0.8214], device='cuda:0')
tensor([0.8214], dtype=torch.float64)
